### PR TITLE
Extend query API for the ResultTracker.  Add the ability to label results, query by label.

### PR DESCRIPTION
**Pull request by sakoht**
#### What this changes:

Getting lists of data that are in storage didn't have a tidy API.

This adds an interface to the ResultTracker to:
- `findFunctionNames`
- `findFunctionVersions`
- `findCallData`
- `findResultData`

An arbitrary value can also be checked to see if and where it has been a result:
- `findResultDataByOutput`

And any result can be checked to see where it has been an input.  The data for this was previously captured, but tracking for this had bugs that are now fixed:
- `findUsesOfResultData`

Or where an arbitrary value has been used as an input:
- `findUsesOfValue`

The methods above work are not fully types, so they can work with types that are not part of the current application/library.  The returned metadata can be fully vivified with a call to `.load` on the metadata, if the application has the associated type available.

The `FunctionWithProvenance` API now has wrappers for the above, plus accessors that vivify fully-typed objects:
- `findCalls`
- `findResults`

This PR also adds the ability to add arbitrary text-string annotation to results.  

The ResultTracker has methods to list tags:
- `findTags`
- `findTagsByOutputType`
- `findTagsByResultFunctionName`

And to look up results by tag:
- `findResultDataByTag`

#### How this was tested:
- [x] New test case `FindSpec`
- [x] New test case `TagSpec`

### CODE REVIEW

**Comment by sakoht** [comment]
I just noticed I didn't complete the README updates.  Updating...

**Comment by sakoht** [comment]
(FYI: I don't have permission to add reviewers or merge this PR when it is approved.)

**Comment by erniebrau** [comment]
> (FYI: I don't have permission to add reviewers or merge this PR when it is approved.)

OK. I haven't had a chance to really look at it. I will make some time today or tomorrow.

I should say that my review will likely be somewhat superficial, as this code uses Scala in a way that is beyond my area of familiarity. Do you have any suggestions about another reviewer we can add?

**Comment by sakoht** [comment]
Joe W did a deep dive with me a bit ago and is very high-level w/ the scala stuff.  Eric and Mike Kiwala have looked at the code less, but more recently.

**Pull request merged**
